[pytest]
filterwarnings =
    ignore:.*ABC.* is deprecated:DeprecationWarning

[pylama:pycodestyle]
max_line_length = 100

[pylama:pylint]
max_line_length = 100

[mypy]
python_version = 3.7
check_untyped_defs = True
disallow_any_generics = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_decorators = True
ignore_errors = False
ignore_missing_imports = True
strict_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
warn_unused_configs = True
